version: '3'

# Setting up the network
networks:
  laravelnetwork:
    driver: bridge

# Setting up the services (containers)
services:
  laravel:
    build: ./
    networks:
      - laravelnetwork
    volumes:
      - ./src/:/var/www/html/
    ports:
      - 8080:80
    # command: chown -R www-data:www-data ./storage/ && chmod -R 775 storage

  mysql:
    image: mysql:8.0
    networks:
      - laravelnetwork
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 9090:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=laravel"

  node:
    image: node:latest
    networks:
      - laravelnetwork
    volumes:
      - ./src/:/var/app/
    ports:
      - 5173:5173
    working_dir: /var/app/
    command: npm install
    entrypoint: npm run dev

  composer:
    image: composer:latest
    volumes:
      - ./src/:/var/app/
    working_dir: /var/app/
    command: composer install